### ISSUE TITLE
Remove dependency on laminas/laminas-zendframework-bridge

### ISSUE THREAD

**Issue by beberlei** [laminas/laminas-eventmanager#21]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.3.1

#### Summary

As documented in this ticket https://github.com/laminas/laminas-zendframework-bridge/issues/83 - the zend framework bridge comes with a heavy autoloader that is only ever needed if someone still uses `Zend` prefixed classes. As such the bridge documents this should only be loaded when needed.

However this component adds the bridge as required dependency, automatically enabling the heavy autoloader for an application with no way to disable it (except resorting to manual autoloader stack manipulation).

#### Current behavior

Loads `laminas/laminas-zendframework-bridge` as dependency

#### Expected behavior

Puts the burden of loading the bridge on the user to decide in their root composer package.

**Comment by Ocramius** [comment]
As discussed in laminas/laminas-zendframework-bridge#83, this is a BC break that can/should be addressed in the next major. All `laminas/*` packages should generally do this.

**Comment by boesing** [comment]
Closing here as it was removed with #22
