### ISSUE TITLE
Dependency abandoned warning on container-interop

### ISSUE THREAD

**Issue by dmetzler1988** [laminas/laminas-eventmanager#23]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.4.0

#### Summary

It's not directly a bug - more a dependency abandoned info.

#### Current behavior

When running `composer require laminas/laminas-eventmanager` i alltimes receive this notification.
``` 
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead
```

#### How to reproduce

If you create a new project, run `composer require laminas/laminas-eventmanager` (after `composer init`).
If you have required on a project, run `composer update laminas/laminas-eventmanager`.

#### Expected behavior

The dependencies are up to date and the abandoned warning is removed.

**Comment by Ocramius** [comment]
This package does not depend on anything at all:

https://github.com/laminas/laminas-eventmanager/blob/9e11e32de9eb66451ddaba81d282cccb9bbf245f/composer.json#L26
