### ISSUE TITLE
The documentation for LazyListeners refers to container-interop

### ISSUE THREAD

**Issue by visto9259** [laminas/laminas-eventmanager#51]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.x

#### Summary

This is a documentation bug.
The documentation on Lazy Listerner is refering to `container-interop` which is no longer used and has been replaced by `Psr\Container`.

**Comment by visto9259** [comment]
I will submit a PR to fix it.

**Comment by Ocramius** [comment]
Handled in #54
