### ISSUE TITLE
The sections "EventManger API" and "Intercepting Filters" do not show in the "root"  level

### ISSUE THREAD

**Issue by visto9259** [laminas/laminas-eventmanager#52]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.x

#### Summary

This is a documentation bug.
The sections "EventManger API" and "Intercepting Filters" do not show in the "root"  level.

#### Current behavior

The sections "EventManger API" and "Intercepting Filters" are showing as under the "Lazy Listeners" section.

**Comment by visto9259** [comment]
I will submit a fix for this

**Comment by visto9259** [comment]
After looking at this further, the issue is not in the documentation for this package but in the rendering of the navigation.  Theses section are under "Reference" where they should be.  It's the rendering of a subsection of a section which is the issue.  Sections and their subsections are not rendering with an indentation that I would have expected.

**Comment by froschdesign** [comment]
@visto9259 
The "Reference" entry is not needed and should be removed. Compare with: https://github.com/laminas/laminas-session/pull/87

> Sections and their subsections are not rendering with an indentation that I would have expected.

Deeper indents are no longer desired and must be removed.

**Comment by visto9259** [comment]
Let me take a look at Session and propose something.

**Comment by visto9259** [comment]
This is how it would look.  I am ready to add it to the PR #53 

![image](https://github.com/laminas/laminas-eventmanager/assets/7890483/3c0dce95-1cb3-40f7-812f-5d4fd4d923eb)

**Comment by froschdesign** [comment]
@visto9259 
Go for it! 👍🏻

**Comment by Ocramius** [comment]
Handled in #54
